kind: pipeline
name: steamcmd

steps:
- name: docker
  image: plugins/docker
  settings:
    dockerfile: Dockerfile
    repo: ich777/steamcmd
    username: ich777
    password:
      from_secret: docker_password
    tags: conanexiles